# Generated by Django 3.1.1 on 2020-10-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='almacen.tipo_producto'),
        ),
    ]
